x-base:
  &base
  env_file:
    - ./.env
  networks:
    - task-rootext
  restart: always

services:
  postgres:
    <<: *base
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    container_name: task-rootext-postgres
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    <<: *base
    image: redis:7.4-alpine
    container_name: task-rootext-redis
    volumes:
      - /redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  migrate:
    <<: *base
    image: migrate/migrate
    container_name: task-rootext-migrate
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "./migrations", "-database", "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?sslmode=disable", "up" ]
    restart: on-failure
    depends_on:
      - postgres

  server:
    <<: *base
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: task-rootext-api
    depends_on:
      - postgres
      - migrate
      - redis

networks:
  task-rootext:
    name: task-rootext
    driver: bridge

volumes:
  postgres-data:
  redis-data:
