app:
  host: 0.0.0.0
  port: 8000
  debug: false
  baseAPI: /api/v1
  secret: LJbu12@344BhnVVV9kPw1
  AccessHourTTL: 24h
  CorsOrigins: [ "*" ]
  CorsMaxAge: 300

postgres:
  host: postgres
  port: 5432
  username: postgres_user
  password: postgres_password
  database: postgres
  MaxOpenConns: 25
  MaxIdleConns: 25
  ConnMaxIdleTime: 15m

redis:
  host: redis
  port: 6379
  password: redis_password