// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Arsham Roshannejad",
            "url": "arshamroshannejad.ir",
            "email": "arshamdev2001@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://www.mit.edu/~amini/LICENSE.md"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Login with register credential",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "make sure send a valid email and password must be grater than 8 character",
                        "name": "loginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_entities.UserAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.LoginOk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.BadRequest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.UserNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Logout and expire jwt token. authenticate required!",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.LogoutOk"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "make sure send a valid email and password must be grater than 8 character",
                        "name": "registerRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_entities.UserAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.UserCreated"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.BadRequest"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.UserExists"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/post": {
            "get": {
                "description": "this endpoint provide all posts. also (pagination, sort, order) is available.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Get All Posts",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "example": 1,
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "example": 3,
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "-vote_count",
                        "example": "created_at -created_at vote_count -vote_count",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.AllPosts"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.BadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.InternalServerError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new post with the provided data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Create a new post",
                "parameters": [
                    {
                        "description": "just send title and text. authenticated required!",
                        "name": "postBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_entities.PostCreateUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.Post"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.BadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/post/{id}": {
            "get": {
                "description": "Get a sing post with id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Get a single post",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.Post"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.PostNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.InternalServerError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update a post with the provided ID and data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Update an existing post",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "just send title and text. authenticated required!",
                        "name": "postBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_entities.PostCreateUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.Post"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.BadRequest"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.Forbidden"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.PostNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.InternalServerError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a post by ID. authenticated required!",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Delete a post",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.Forbidden"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.PostNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/post/{id}/vote": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add a vote for a post by ID. authenticated required!",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Add a vote to a post",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "value must 1 or -1",
                        "name": "voteBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_entities.VoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.VoteSuccessful"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.BadRequest"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.Forbidden"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.PostNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.InternalServerError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove a vote for a post by ID. authenticated required!",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Remove a vote from a post",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.PostNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.InternalServerError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_arshamroshannejad_task-rootext_internal_entities.PostCreateUpdateRequest": {
            "type": "object",
            "required": [
                "text",
                "title"
            ],
            "properties": {
                "text": {
                    "type": "string",
                    "example": "Content of my new post."
                },
                "title": {
                    "type": "string",
                    "example": "My New Post"
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_entities.UserAuthRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "james@gmail.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "1qaz2wsx"
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_entities.VoteRequest": {
            "type": "object",
            "required": [
                "value"
            ],
            "properties": {
                "value": {
                    "type": "string",
                    "enum": [
                        "1",
                        "-1"
                    ],
                    "example": "-1"
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_helpers.AllPosts": {
            "type": "object",
            "properties": {
                "metadata": {
                    "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_helpers.Metadata"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_arshamroshannejad_task-rootext_internal_model.Post"
                    }
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_helpers.BadRequest": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "bad request"
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_helpers.Forbidden": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Forbidden"
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_helpers.InternalServerError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Internal Server Error"
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_helpers.LoginOk": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_helpers.LogoutOk": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "string",
                    "example": "logged out"
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_helpers.Metadata": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer",
                    "example": 3
                },
                "first_page": {
                    "type": "integer",
                    "example": 1
                },
                "last_page": {
                    "type": "integer",
                    "example": 12
                },
                "page_size": {
                    "type": "integer",
                    "example": 2
                },
                "total_records": {
                    "type": "integer",
                    "example": 1200
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_helpers.Post": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-10-27T10:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "1"
                },
                "text": {
                    "type": "string",
                    "example": "This is the content of my first post."
                },
                "title": {
                    "type": "string",
                    "example": "My First Post"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-10-27T10:30:00Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "123"
                },
                "vote_count": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_helpers.PostNotFound": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "post not found"
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_helpers.UserCreated": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "string",
                    "example": "user created"
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_helpers.UserExists": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "user already exists"
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_helpers.UserNotFound": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "user not found"
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_helpers.VoteSuccessful": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "string",
                    "example": "successful"
                }
            }
        },
        "github_com_arshamroshannejad_task-rootext_internal_model.Post": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-10-27T10:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "1"
                },
                "text": {
                    "type": "string",
                    "example": "This is the content of my first post."
                },
                "title": {
                    "type": "string",
                    "example": "My First Post"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-10-27T10:30:00Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "123"
                },
                "vote_count": {
                    "type": "integer",
                    "example": 100
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "task-rootext",
	Description:      "API like reddit application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
